name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/ph-exam.png
    - assets/page-1/images/ph-teacher.png
    - assets/page-1/images/imgtextbook.png
    - assets/page-1/images/healthicons-i-exam-qualification-outline.png
    - assets/page-1/images/material-symbols-cancel.png
    - assets/page-1/images/material-symbols-check-circle.png
    - assets/page-1/images/imgtextbook-8LD.png
    - assets/page-1/images/iconhome.png
    - assets/page-1/images/icondarkmode.png
    - assets/page-1/images/ellipse-bg.png
    - assets/page-1/images/buttonadd.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/iconhome-PzD.png
    - assets/page-1/images/iconfaltas.png
    - assets/page-1/images/iconhorario.png
    - assets/page-1/images/icondarkmode-6PP.png
    - assets/page-1/images/rectangle-9.png
    - assets/page-1/images/ph-exam-Qih.png
    - assets/page-1/images/iconhome-ayB.png
    - assets/page-1/images/rectangle-11.png
    - assets/page-1/images/buttonadd-ond.png
    - assets/page-1/images/iconfaltas-KJM.png
    - assets/page-1/images/ph-teacher-nj7.png
    - assets/page-1/images/iconcarrera.png
    - assets/page-1/images/ci-share.png
    - assets/page-1/images/iconcarrera-Hcy.png
    - assets/page-1/images/iconfaltas-b7s.png
    - assets/page-1/images/ph-teacher-eoX.png
    - assets/page-1/images/rectangle-9-8yb.png
    - assets/page-1/images/rectangle-10.png
    - assets/page-1/images/ellipse-bg-xtd.png
    - assets/page-1/images/rectangle-9-9YR.png
    - assets/page-1/images/icondarkmode-TJD.png
    - assets/page-1/images/ph-exam-zJ9.png
    - assets/page-1/images/ellipse-bg-ijw.png
    - assets/page-1/images/rectangle-9-Dad.png
    - assets/page-1/images/fa-regular-calendar-times.png
    - assets/page-1/images/rectangle-9-33s.png
    - assets/page-1/images/iconhorario-MqF.png
    - assets/page-1/images/iconfaltas-uNu.png
    - assets/page-1/images/rectangle-9-1wj.png
    - assets/page-1/images/ellipse-bg-9Y9.png
    - assets/page-1/images/ph-exam-cTf.png
    - assets/page-1/images/iconuser.png
    - assets/page-1/images/vector-hED.png
    - assets/page-1/images/iconhorario-ppd.png
    - assets/page-1/images/iconhome-WL5.png
    - assets/page-1/images/rectangle-9-Zbj.png
    - assets/page-1/images/ic-twotone-email.png
    - assets/page-1/images/material-symbols-auto-schedule.png
    - assets/page-1/images/ellipse-bg-hHo.png
    - assets/page-1/images/fluent-mdl2-total.png
    - assets/page-1/images/rectangle-11-Rd7.png
    - assets/page-1/images/rectangle-11-WuT.png
    - assets/page-1/images/mingcute-counter-line.png
    - assets/page-1/images/ph-exam-Lso.png
    - assets/page-1/images/textbook.png
    - assets/page-1/images/vector-ECV.png
    - assets/page-1/images/iconfaltas-kwX.png
    - assets/page-1/images/mingcute-book-2-line.png
    - assets/page-1/images/iconhome-j2d.png
    - assets/page-1/images/rectangle-bg.png
    - assets/page-1/images/rectangle-bg-fJu.png
    - assets/page-1/images/rectangle-bg-Z9P.png
    - assets/page-1/images/iconhorario-gjo.png
    - assets/page-1/images/rectangle-9-PV7.png
    - assets/page-1/images/ic-baseline-phone.png
    - assets/page-1/images/icondarkmode-xq3.png
    - assets/page-1/images/iconhorario-hw3.png
    - assets/page-1/images/rectangle.png
    - assets/page-1/images/icondarkmode-cbw.png
    - assets/page-1/images/rectangle-bg-e3P.png
    - assets/page-1/images/icondarkmode-jth.png
    - assets/page-1/images/vector-EMb.png
    - assets/page-1/images/buttonadd-1gR.png
    - assets/page-1/images/ph-teacher-Qtu.png
    - assets/page-1/images/property-1default.png
    - assets/page-1/images/property-1variant2.png
    - assets/page-1/images/vector-WhK.png
    - assets/page-1/images/rectangle-bg-BEu.png
    - assets/page-1/images/auto-group-p75o.png
    - assets/page-1/images/ph-teacher-EmK.png
    - assets/page-1/images/rectangle-9-YX7.png
    - assets/page-1/images/mdi-about.png
    - assets/page-1/images/iconfaltas-RC9.png
    - assets/page-1/images/auto-group-hfqh.png
    - assets/page-1/images/ellipse.png
    - assets/page-1/images/material-symbols-close.png
    - assets/page-1/images/vector-RLZ.png
    - assets/page-1/images/vector-p1s.png
    - assets/page-1/images/ph-teacher-gJy.png
    - assets/page-1/images/bxs-book.png
    - assets/page-1/images/rectangle-bg-GSh.png
    - assets/page-1/images/vector-9Fb.png
    - assets/page-1/images/rectangle-bg-qeD.png
    - assets/page-1/images/iconhorario-NPF.png
    - assets/page-1/images/vector-o5o.png
    - assets/page-1/images/rectangle-9-h3K.png
    - assets/page-1/images/vector-Cq3.png
    - assets/page-1/images/ci-share-auT.png
    - assets/page-1/images/mdi-question-mark-circle.png
    - assets/page-1/images/ph-exam-MWD.png
    - assets/page-1/images/vector-jn5.png
    - assets/page-1/images/iconhome-RRw.png
    - assets/page-1/images/material-symbols-close-aNh.png
    - assets/page-1/images/rectangle-bg-s4H.png
    - assets/page-1/images/vector-VA5.png
    - assets/page-1/images/iconuser-QcM.png
    - assets/page-1/images/rectangle-11-Pq7.png
    - assets/page-1/images/textbook-FNm.png
    - assets/page-1/images/material-symbols-close-2vH.png
    - assets/page-1/images/ph-smiley-sad.png
    - assets/page-1/images/ellipse-bg-YDT.png
    - assets/page-1/images/bi-emoji-smile.png
    - assets/page-1/images/material-symbols-close-GuB.png
    - assets/page-1/images/rectangle-bg-YGm.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
